site_name: BAPCtools
site_description: Documentation for BAPCtools
site_url: https://RagnarGrootKoerkamp.github.io/BAPCtools/

theme:
  name: material

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
