#!/usr/bin/env bash

# Build the required validators.
# Modify to your likings.
# The following aliases are guaranteed to exist:
# python3: for a Python 3 interpreter
# cc: for a c ompiler
# c++: for a c++ compiler

for validator in *.cpp ; do
	c++ -std=gnu++17 -Wall -Wextra -pedantic -O2 $validator -o ${validator%.cpp}
done
