#!/usr/bin/env sh

# the package format defines that cc is an alias for a c compiler
cc -g -O1 -Wall -fstack-protector -D_FORTIFY_SOURCE=2 -fPIE -Wformat -Wformat-security -ansi -pedantic runjury_boolfind.c -o jury
