#!/usr/bin/env sh

set -e

draw=false
for var in "$@"
do
    [ "$var" = "--draw-please" ] && draw=true
done

if [ "$draw" = true ]; then
	asy -f png $(dirname $0)/visualize.asy -u infilename="'${1}'" -u ansfilename="'${2}'" -o $3/judgeimage.png
fi
