#!/bin/sh

# A script (shell or python) to run the generators.
# You can call your generator multiple times with different command line arguments,
# or write a generator that writes multiple files with a single call.
# This script will always be called with the `generators` directory as working directory.

# All generated .in and .ans files must be written to `data/secret/`,
# and MUST INCLUDE A PREFIX BETWEEN 00 AND 99.

# ALL GENERATORS MUST BE DETERMINISTIC
# If you want to use e.g. `rand()`, please call `srand()` with some constant.
