name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container: ragnargrootkoerkamp/bapctools
    steps:
      - uses: actions/checkout@v2
      - run: cue vet doc/generators.yaml support/schemas/*cue -d '#Generators'
      - run: pytest
